# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aniket/BallAlgo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aniket/BallAlgo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/aniket/.local/lib/python3.13/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aniket/BallAlgo/CMakeFiles /home/aniket/BallAlgo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aniket/BallAlgo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ballalgo_motion_core

# Build rule for target.
ballalgo_motion_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo_motion_core
.PHONY : ballalgo_motion_core

# fast build rule for target.
ballalgo_motion_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/build
.PHONY : ballalgo_motion_core/fast

#=============================================================================
# Target rules for targets named ballalgo_planner_case

# Build rule for target.
ballalgo_planner_case: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo_planner_case
.PHONY : ballalgo_planner_case

# fast build rule for target.
ballalgo_planner_case/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/build
.PHONY : ballalgo_planner_case/fast

#=============================================================================
# Target rules for targets named ballalgo

# Build rule for target.
ballalgo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo
.PHONY : ballalgo

# fast build rule for target.
ballalgo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/build
.PHONY : ballalgo/fast

#=============================================================================
# Target rules for targets named ballalgo_team_tests

# Build rule for target.
ballalgo_team_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo_team_tests
.PHONY : ballalgo_team_tests

# fast build rule for target.
ballalgo_team_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/build
.PHONY : ballalgo_team_tests/fast

#=============================================================================
# Target rules for targets named ballalgo_motion_tests

# Build rule for target.
ballalgo_motion_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo_motion_tests
.PHONY : ballalgo_motion_tests

# fast build rule for target.
ballalgo_motion_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_tests.dir/build.make CMakeFiles/ballalgo_motion_tests.dir/build
.PHONY : ballalgo_motion_tests/fast

#=============================================================================
# Target rules for targets named ballalgo_protocol_tests

# Build rule for target.
ballalgo_protocol_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo_protocol_tests
.PHONY : ballalgo_protocol_tests

# fast build rule for target.
ballalgo_protocol_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_protocol_tests.dir/build.make CMakeFiles/ballalgo_protocol_tests.dir/build
.PHONY : ballalgo_protocol_tests/fast

#=============================================================================
# Target rules for targets named ballalgo_frame_tests

# Build rule for target.
ballalgo_frame_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo_frame_tests
.PHONY : ballalgo_frame_tests

# fast build rule for target.
ballalgo_frame_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_frame_tests.dir/build.make CMakeFiles/ballalgo_frame_tests.dir/build
.PHONY : ballalgo_frame_tests/fast

src/FoxGloveSim/FoxgloveConfig.o: src/FoxGloveSim/FoxgloveConfig.cpp.o
.PHONY : src/FoxGloveSim/FoxgloveConfig.o

# target to build an object file
src/FoxGloveSim/FoxgloveConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/FoxGloveSim/FoxgloveConfig.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveConfig.cpp.o
.PHONY : src/FoxGloveSim/FoxgloveConfig.cpp.o

src/FoxGloveSim/FoxgloveConfig.i: src/FoxGloveSim/FoxgloveConfig.cpp.i
.PHONY : src/FoxGloveSim/FoxgloveConfig.i

# target to preprocess a source file
src/FoxGloveSim/FoxgloveConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/FoxGloveSim/FoxgloveConfig.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveConfig.cpp.i
.PHONY : src/FoxGloveSim/FoxgloveConfig.cpp.i

src/FoxGloveSim/FoxgloveConfig.s: src/FoxGloveSim/FoxgloveConfig.cpp.s
.PHONY : src/FoxGloveSim/FoxgloveConfig.s

# target to generate assembly for a file
src/FoxGloveSim/FoxgloveConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/FoxGloveSim/FoxgloveConfig.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveConfig.cpp.s
.PHONY : src/FoxGloveSim/FoxgloveConfig.cpp.s

src/FoxGloveSim/FoxgloveTelemetryPublisher.o: src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.o
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.o

# target to build an object file
src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.o
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.o

src/FoxGloveSim/FoxgloveTelemetryPublisher.i: src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.i
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.i

# target to preprocess a source file
src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.i
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.i

src/FoxGloveSim/FoxgloveTelemetryPublisher.s: src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.s
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.s

# target to generate assembly for a file
src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.s
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.s

src/camera/CameraCapture.o: src/camera/CameraCapture.cpp.o
.PHONY : src/camera/CameraCapture.o

# target to build an object file
src/camera/CameraCapture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/camera/CameraCapture.cpp.o
.PHONY : src/camera/CameraCapture.cpp.o

src/camera/CameraCapture.i: src/camera/CameraCapture.cpp.i
.PHONY : src/camera/CameraCapture.i

# target to preprocess a source file
src/camera/CameraCapture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/camera/CameraCapture.cpp.i
.PHONY : src/camera/CameraCapture.cpp.i

src/camera/CameraCapture.s: src/camera/CameraCapture.cpp.s
.PHONY : src/camera/CameraCapture.s

# target to generate assembly for a file
src/camera/CameraCapture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/camera/CameraCapture.cpp.s
.PHONY : src/camera/CameraCapture.cpp.s

src/estimation/BallKalman.o: src/estimation/BallKalman.cpp.o
.PHONY : src/estimation/BallKalman.o

# target to build an object file
src/estimation/BallKalman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/BallKalman.cpp.o
.PHONY : src/estimation/BallKalman.cpp.o

src/estimation/BallKalman.i: src/estimation/BallKalman.cpp.i
.PHONY : src/estimation/BallKalman.i

# target to preprocess a source file
src/estimation/BallKalman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/BallKalman.cpp.i
.PHONY : src/estimation/BallKalman.cpp.i

src/estimation/BallKalman.s: src/estimation/BallKalman.cpp.s
.PHONY : src/estimation/BallKalman.s

# target to generate assembly for a file
src/estimation/BallKalman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/BallKalman.cpp.s
.PHONY : src/estimation/BallKalman.cpp.s

src/estimation/PoseKalman.o: src/estimation/PoseKalman.cpp.o
.PHONY : src/estimation/PoseKalman.o

# target to build an object file
src/estimation/PoseKalman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/PoseKalman.cpp.o
.PHONY : src/estimation/PoseKalman.cpp.o

src/estimation/PoseKalman.i: src/estimation/PoseKalman.cpp.i
.PHONY : src/estimation/PoseKalman.i

# target to preprocess a source file
src/estimation/PoseKalman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/PoseKalman.cpp.i
.PHONY : src/estimation/PoseKalman.cpp.i

src/estimation/PoseKalman.s: src/estimation/PoseKalman.cpp.s
.PHONY : src/estimation/PoseKalman.s

# target to generate assembly for a file
src/estimation/PoseKalman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/PoseKalman.cpp.s
.PHONY : src/estimation/PoseKalman.cpp.s

src/io/GpioLidar.o: src/io/GpioLidar.cpp.o
.PHONY : src/io/GpioLidar.o

# target to build an object file
src/io/GpioLidar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/GpioLidar.cpp.o
.PHONY : src/io/GpioLidar.cpp.o

src/io/GpioLidar.i: src/io/GpioLidar.cpp.i
.PHONY : src/io/GpioLidar.i

# target to preprocess a source file
src/io/GpioLidar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/GpioLidar.cpp.i
.PHONY : src/io/GpioLidar.cpp.i

src/io/GpioLidar.s: src/io/GpioLidar.cpp.s
.PHONY : src/io/GpioLidar.s

# target to generate assembly for a file
src/io/GpioLidar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/GpioLidar.cpp.s
.PHONY : src/io/GpioLidar.cpp.s

src/io/RobotSerial.o: src/io/RobotSerial.cpp.o
.PHONY : src/io/RobotSerial.o

# target to build an object file
src/io/RobotSerial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/io/RobotSerial.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/RobotSerial.cpp.o
.PHONY : src/io/RobotSerial.cpp.o

src/io/RobotSerial.i: src/io/RobotSerial.cpp.i
.PHONY : src/io/RobotSerial.i

# target to preprocess a source file
src/io/RobotSerial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/io/RobotSerial.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/RobotSerial.cpp.i
.PHONY : src/io/RobotSerial.cpp.i

src/io/RobotSerial.s: src/io/RobotSerial.cpp.s
.PHONY : src/io/RobotSerial.s

# target to generate assembly for a file
src/io/RobotSerial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/io/RobotSerial.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/RobotSerial.cpp.s
.PHONY : src/io/RobotSerial.cpp.s

src/lidar/Ld19Reader.o: src/lidar/Ld19Reader.cpp.o
.PHONY : src/lidar/Ld19Reader.o

# target to build an object file
src/lidar/Ld19Reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/Ld19Reader.cpp.o
.PHONY : src/lidar/Ld19Reader.cpp.o

src/lidar/Ld19Reader.i: src/lidar/Ld19Reader.cpp.i
.PHONY : src/lidar/Ld19Reader.i

# target to preprocess a source file
src/lidar/Ld19Reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/Ld19Reader.cpp.i
.PHONY : src/lidar/Ld19Reader.cpp.i

src/lidar/Ld19Reader.s: src/lidar/Ld19Reader.cpp.s
.PHONY : src/lidar/Ld19Reader.s

# target to generate assembly for a file
src/lidar/Ld19Reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/Ld19Reader.cpp.s
.PHONY : src/lidar/Ld19Reader.cpp.s

src/lidar/LidarDeskewer.o: src/lidar/LidarDeskewer.cpp.o
.PHONY : src/lidar/LidarDeskewer.o

# target to build an object file
src/lidar/LidarDeskewer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/LidarDeskewer.cpp.o
.PHONY : src/lidar/LidarDeskewer.cpp.o

src/lidar/LidarDeskewer.i: src/lidar/LidarDeskewer.cpp.i
.PHONY : src/lidar/LidarDeskewer.i

# target to preprocess a source file
src/lidar/LidarDeskewer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/LidarDeskewer.cpp.i
.PHONY : src/lidar/LidarDeskewer.cpp.i

src/lidar/LidarDeskewer.s: src/lidar/LidarDeskewer.cpp.s
.PHONY : src/lidar/LidarDeskewer.s

# target to generate assembly for a file
src/lidar/LidarDeskewer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/LidarDeskewer.cpp.s
.PHONY : src/lidar/LidarDeskewer.cpp.s

src/lidar/LidarLocalizer.o: src/lidar/LidarLocalizer.cpp.o
.PHONY : src/lidar/LidarLocalizer.o

# target to build an object file
src/lidar/LidarLocalizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/LidarLocalizer.cpp.o
.PHONY : src/lidar/LidarLocalizer.cpp.o

src/lidar/LidarLocalizer.i: src/lidar/LidarLocalizer.cpp.i
.PHONY : src/lidar/LidarLocalizer.i

# target to preprocess a source file
src/lidar/LidarLocalizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/LidarLocalizer.cpp.i
.PHONY : src/lidar/LidarLocalizer.cpp.i

src/lidar/LidarLocalizer.s: src/lidar/LidarLocalizer.cpp.s
.PHONY : src/lidar/LidarLocalizer.s

# target to generate assembly for a file
src/lidar/LidarLocalizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/LidarLocalizer.cpp.s
.PHONY : src/lidar/LidarLocalizer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/motion/AStar3D.o: src/motion/AStar3D.cpp.o
.PHONY : src/motion/AStar3D.o

# target to build an object file
src/motion/AStar3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/AStar3D.cpp.o
.PHONY : src/motion/AStar3D.cpp.o

src/motion/AStar3D.i: src/motion/AStar3D.cpp.i
.PHONY : src/motion/AStar3D.i

# target to preprocess a source file
src/motion/AStar3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/AStar3D.cpp.i
.PHONY : src/motion/AStar3D.cpp.i

src/motion/AStar3D.s: src/motion/AStar3D.cpp.s
.PHONY : src/motion/AStar3D.s

# target to generate assembly for a file
src/motion/AStar3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/AStar3D.cpp.s
.PHONY : src/motion/AStar3D.cpp.s

src/motion/ActionChunkPublisher.o: src/motion/ActionChunkPublisher.cpp.o
.PHONY : src/motion/ActionChunkPublisher.o

# target to build an object file
src/motion/ActionChunkPublisher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ActionChunkPublisher.cpp.o
.PHONY : src/motion/ActionChunkPublisher.cpp.o

src/motion/ActionChunkPublisher.i: src/motion/ActionChunkPublisher.cpp.i
.PHONY : src/motion/ActionChunkPublisher.i

# target to preprocess a source file
src/motion/ActionChunkPublisher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ActionChunkPublisher.cpp.i
.PHONY : src/motion/ActionChunkPublisher.cpp.i

src/motion/ActionChunkPublisher.s: src/motion/ActionChunkPublisher.cpp.s
.PHONY : src/motion/ActionChunkPublisher.s

# target to generate assembly for a file
src/motion/ActionChunkPublisher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ActionChunkPublisher.cpp.s
.PHONY : src/motion/ActionChunkPublisher.cpp.s

src/motion/ClockSync.o: src/motion/ClockSync.cpp.o
.PHONY : src/motion/ClockSync.o

# target to build an object file
src/motion/ClockSync.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/motion/ClockSync.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ClockSync.cpp.o
.PHONY : src/motion/ClockSync.cpp.o

src/motion/ClockSync.i: src/motion/ClockSync.cpp.i
.PHONY : src/motion/ClockSync.i

# target to preprocess a source file
src/motion/ClockSync.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/motion/ClockSync.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ClockSync.cpp.i
.PHONY : src/motion/ClockSync.cpp.i

src/motion/ClockSync.s: src/motion/ClockSync.cpp.s
.PHONY : src/motion/ClockSync.s

# target to generate assembly for a file
src/motion/ClockSync.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/motion/ClockSync.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ClockSync.cpp.s
.PHONY : src/motion/ClockSync.cpp.s

src/motion/DefensePose.o: src/motion/DefensePose.cpp.o
.PHONY : src/motion/DefensePose.o

# target to build an object file
src/motion/DefensePose.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/DefensePose.cpp.o
.PHONY : src/motion/DefensePose.cpp.o

src/motion/DefensePose.i: src/motion/DefensePose.cpp.i
.PHONY : src/motion/DefensePose.i

# target to preprocess a source file
src/motion/DefensePose.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/DefensePose.cpp.i
.PHONY : src/motion/DefensePose.cpp.i

src/motion/DefensePose.s: src/motion/DefensePose.cpp.s
.PHONY : src/motion/DefensePose.s

# target to generate assembly for a file
src/motion/DefensePose.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/DefensePose.cpp.s
.PHONY : src/motion/DefensePose.cpp.s

src/motion/HermiteSpline.o: src/motion/HermiteSpline.cpp.o
.PHONY : src/motion/HermiteSpline.o

# target to build an object file
src/motion/HermiteSpline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/HermiteSpline.cpp.o
.PHONY : src/motion/HermiteSpline.cpp.o

src/motion/HermiteSpline.i: src/motion/HermiteSpline.cpp.i
.PHONY : src/motion/HermiteSpline.i

# target to preprocess a source file
src/motion/HermiteSpline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/HermiteSpline.cpp.i
.PHONY : src/motion/HermiteSpline.cpp.i

src/motion/HermiteSpline.s: src/motion/HermiteSpline.cpp.s
.PHONY : src/motion/HermiteSpline.s

# target to generate assembly for a file
src/motion/HermiteSpline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/HermiteSpline.cpp.s
.PHONY : src/motion/HermiteSpline.cpp.s

src/motion/MotionPipeline.o: src/motion/MotionPipeline.cpp.o
.PHONY : src/motion/MotionPipeline.o

# target to build an object file
src/motion/MotionPipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/MotionPipeline.cpp.o
.PHONY : src/motion/MotionPipeline.cpp.o

src/motion/MotionPipeline.i: src/motion/MotionPipeline.cpp.i
.PHONY : src/motion/MotionPipeline.i

# target to preprocess a source file
src/motion/MotionPipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/MotionPipeline.cpp.i
.PHONY : src/motion/MotionPipeline.cpp.i

src/motion/MotionPipeline.s: src/motion/MotionPipeline.cpp.s
.PHONY : src/motion/MotionPipeline.s

# target to generate assembly for a file
src/motion/MotionPipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/MotionPipeline.cpp.s
.PHONY : src/motion/MotionPipeline.cpp.s

src/motion/MotionPlanner.o: src/motion/MotionPlanner.cpp.o
.PHONY : src/motion/MotionPlanner.o

# target to build an object file
src/motion/MotionPlanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/MotionPlanner.cpp.o
.PHONY : src/motion/MotionPlanner.cpp.o

src/motion/MotionPlanner.i: src/motion/MotionPlanner.cpp.i
.PHONY : src/motion/MotionPlanner.i

# target to preprocess a source file
src/motion/MotionPlanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/MotionPlanner.cpp.i
.PHONY : src/motion/MotionPlanner.cpp.i

src/motion/MotionPlanner.s: src/motion/MotionPlanner.cpp.s
.PHONY : src/motion/MotionPlanner.s

# target to generate assembly for a file
src/motion/MotionPlanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/MotionPlanner.cpp.s
.PHONY : src/motion/MotionPlanner.cpp.s

src/motion/OffensePose.o: src/motion/OffensePose.cpp.o
.PHONY : src/motion/OffensePose.o

# target to build an object file
src/motion/OffensePose.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/OffensePose.cpp.o
.PHONY : src/motion/OffensePose.cpp.o

src/motion/OffensePose.i: src/motion/OffensePose.cpp.i
.PHONY : src/motion/OffensePose.i

# target to preprocess a source file
src/motion/OffensePose.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/OffensePose.cpp.i
.PHONY : src/motion/OffensePose.cpp.i

src/motion/OffensePose.s: src/motion/OffensePose.cpp.s
.PHONY : src/motion/OffensePose.s

# target to generate assembly for a file
src/motion/OffensePose.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/OffensePose.cpp.s
.PHONY : src/motion/OffensePose.cpp.s

src/motion/Protocol.o: src/motion/Protocol.cpp.o
.PHONY : src/motion/Protocol.o

# target to build an object file
src/motion/Protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/motion/Protocol.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/Protocol.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_protocol_tests.dir/build.make CMakeFiles/ballalgo_protocol_tests.dir/src/motion/Protocol.cpp.o
.PHONY : src/motion/Protocol.cpp.o

src/motion/Protocol.i: src/motion/Protocol.cpp.i
.PHONY : src/motion/Protocol.i

# target to preprocess a source file
src/motion/Protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/motion/Protocol.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/Protocol.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_protocol_tests.dir/build.make CMakeFiles/ballalgo_protocol_tests.dir/src/motion/Protocol.cpp.i
.PHONY : src/motion/Protocol.cpp.i

src/motion/Protocol.s: src/motion/Protocol.cpp.s
.PHONY : src/motion/Protocol.s

# target to generate assembly for a file
src/motion/Protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/motion/Protocol.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/Protocol.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_protocol_tests.dir/build.make CMakeFiles/ballalgo_protocol_tests.dir/src/motion/Protocol.cpp.s
.PHONY : src/motion/Protocol.cpp.s

src/motion/StrikePose.o: src/motion/StrikePose.cpp.o
.PHONY : src/motion/StrikePose.o

# target to build an object file
src/motion/StrikePose.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/StrikePose.cpp.o
.PHONY : src/motion/StrikePose.cpp.o

src/motion/StrikePose.i: src/motion/StrikePose.cpp.i
.PHONY : src/motion/StrikePose.i

# target to preprocess a source file
src/motion/StrikePose.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/StrikePose.cpp.i
.PHONY : src/motion/StrikePose.cpp.i

src/motion/StrikePose.s: src/motion/StrikePose.cpp.s
.PHONY : src/motion/StrikePose.s

# target to generate assembly for a file
src/motion/StrikePose.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/StrikePose.cpp.s
.PHONY : src/motion/StrikePose.cpp.s

src/motion/TrajectoryReplay.o: src/motion/TrajectoryReplay.cpp.o
.PHONY : src/motion/TrajectoryReplay.o

# target to build an object file
src/motion/TrajectoryReplay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/TrajectoryReplay.cpp.o
.PHONY : src/motion/TrajectoryReplay.cpp.o

src/motion/TrajectoryReplay.i: src/motion/TrajectoryReplay.cpp.i
.PHONY : src/motion/TrajectoryReplay.i

# target to preprocess a source file
src/motion/TrajectoryReplay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/TrajectoryReplay.cpp.i
.PHONY : src/motion/TrajectoryReplay.cpp.i

src/motion/TrajectoryReplay.s: src/motion/TrajectoryReplay.cpp.s
.PHONY : src/motion/TrajectoryReplay.s

# target to generate assembly for a file
src/motion/TrajectoryReplay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/TrajectoryReplay.cpp.s
.PHONY : src/motion/TrajectoryReplay.cpp.s

src/motion/TrajectoryReplayRunner.o: src/motion/TrajectoryReplayRunner.cpp.o
.PHONY : src/motion/TrajectoryReplayRunner.o

# target to build an object file
src/motion/TrajectoryReplayRunner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/motion/TrajectoryReplayRunner.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/TrajectoryReplayRunner.cpp.o
.PHONY : src/motion/TrajectoryReplayRunner.cpp.o

src/motion/TrajectoryReplayRunner.i: src/motion/TrajectoryReplayRunner.cpp.i
.PHONY : src/motion/TrajectoryReplayRunner.i

# target to preprocess a source file
src/motion/TrajectoryReplayRunner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/motion/TrajectoryReplayRunner.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/TrajectoryReplayRunner.cpp.i
.PHONY : src/motion/TrajectoryReplayRunner.cpp.i

src/motion/TrajectoryReplayRunner.s: src/motion/TrajectoryReplayRunner.cpp.s
.PHONY : src/motion/TrajectoryReplayRunner.s

# target to generate assembly for a file
src/motion/TrajectoryReplayRunner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/motion/TrajectoryReplayRunner.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/TrajectoryReplayRunner.cpp.s
.PHONY : src/motion/TrajectoryReplayRunner.cpp.s

src/motion/VelocityProfile.o: src/motion/VelocityProfile.cpp.o
.PHONY : src/motion/VelocityProfile.o

# target to build an object file
src/motion/VelocityProfile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/VelocityProfile.cpp.o
.PHONY : src/motion/VelocityProfile.cpp.o

src/motion/VelocityProfile.i: src/motion/VelocityProfile.cpp.i
.PHONY : src/motion/VelocityProfile.i

# target to preprocess a source file
src/motion/VelocityProfile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/VelocityProfile.cpp.i
.PHONY : src/motion/VelocityProfile.cpp.i

src/motion/VelocityProfile.s: src/motion/VelocityProfile.cpp.s
.PHONY : src/motion/VelocityProfile.s

# target to generate assembly for a file
src/motion/VelocityProfile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/VelocityProfile.cpp.s
.PHONY : src/motion/VelocityProfile.cpp.s

src/planner/PlannerCaseMain.o: src/planner/PlannerCaseMain.cpp.o
.PHONY : src/planner/PlannerCaseMain.o

# target to build an object file
src/planner/PlannerCaseMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/planner/PlannerCaseMain.cpp.o
.PHONY : src/planner/PlannerCaseMain.cpp.o

src/planner/PlannerCaseMain.i: src/planner/PlannerCaseMain.cpp.i
.PHONY : src/planner/PlannerCaseMain.i

# target to preprocess a source file
src/planner/PlannerCaseMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/planner/PlannerCaseMain.cpp.i
.PHONY : src/planner/PlannerCaseMain.cpp.i

src/planner/PlannerCaseMain.s: src/planner/PlannerCaseMain.cpp.s
.PHONY : src/planner/PlannerCaseMain.s

# target to generate assembly for a file
src/planner/PlannerCaseMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_case.dir/build.make CMakeFiles/ballalgo_planner_case.dir/src/planner/PlannerCaseMain.cpp.s
.PHONY : src/planner/PlannerCaseMain.cpp.s

src/team/RoleArbiter.o: src/team/RoleArbiter.cpp.o
.PHONY : src/team/RoleArbiter.o

# target to build an object file
src/team/RoleArbiter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/RoleArbiter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/team/RoleArbiter.cpp.o
.PHONY : src/team/RoleArbiter.cpp.o

src/team/RoleArbiter.i: src/team/RoleArbiter.cpp.i
.PHONY : src/team/RoleArbiter.i

# target to preprocess a source file
src/team/RoleArbiter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/RoleArbiter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/team/RoleArbiter.cpp.i
.PHONY : src/team/RoleArbiter.cpp.i

src/team/RoleArbiter.s: src/team/RoleArbiter.cpp.s
.PHONY : src/team/RoleArbiter.s

# target to generate assembly for a file
src/team/RoleArbiter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/RoleArbiter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/team/RoleArbiter.cpp.s
.PHONY : src/team/RoleArbiter.cpp.s

src/team/TeamBallFilter.o: src/team/TeamBallFilter.cpp.o
.PHONY : src/team/TeamBallFilter.o

# target to build an object file
src/team/TeamBallFilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/TeamBallFilter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/team/TeamBallFilter.cpp.o
.PHONY : src/team/TeamBallFilter.cpp.o

src/team/TeamBallFilter.i: src/team/TeamBallFilter.cpp.i
.PHONY : src/team/TeamBallFilter.i

# target to preprocess a source file
src/team/TeamBallFilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/TeamBallFilter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/team/TeamBallFilter.cpp.i
.PHONY : src/team/TeamBallFilter.cpp.i

src/team/TeamBallFilter.s: src/team/TeamBallFilter.cpp.s
.PHONY : src/team/TeamBallFilter.s

# target to generate assembly for a file
src/team/TeamBallFilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/TeamBallFilter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/team/TeamBallFilter.cpp.s
.PHONY : src/team/TeamBallFilter.cpp.s

src/team/TeamLink.o: src/team/TeamLink.cpp.o
.PHONY : src/team/TeamLink.o

# target to build an object file
src/team/TeamLink.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/TeamLink.cpp.o
.PHONY : src/team/TeamLink.cpp.o

src/team/TeamLink.i: src/team/TeamLink.cpp.i
.PHONY : src/team/TeamLink.i

# target to preprocess a source file
src/team/TeamLink.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/TeamLink.cpp.i
.PHONY : src/team/TeamLink.cpp.i

src/team/TeamLink.s: src/team/TeamLink.cpp.s
.PHONY : src/team/TeamLink.s

# target to generate assembly for a file
src/team/TeamLink.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/TeamLink.cpp.s
.PHONY : src/team/TeamLink.cpp.s

src/team/TeamProto.o: src/team/TeamProto.cpp.o
.PHONY : src/team/TeamProto.o

# target to build an object file
src/team/TeamProto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/TeamProto.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/team/TeamProto.cpp.o
.PHONY : src/team/TeamProto.cpp.o

src/team/TeamProto.i: src/team/TeamProto.cpp.i
.PHONY : src/team/TeamProto.i

# target to preprocess a source file
src/team/TeamProto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/TeamProto.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/team/TeamProto.cpp.i
.PHONY : src/team/TeamProto.cpp.i

src/team/TeamProto.s: src/team/TeamProto.cpp.s
.PHONY : src/team/TeamProto.s

# target to generate assembly for a file
src/team/TeamProto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/team/TeamProto.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/team/TeamProto.cpp.s
.PHONY : src/team/TeamProto.cpp.s

src/vision/SectorTracker.o: src/vision/SectorTracker.cpp.o
.PHONY : src/vision/SectorTracker.o

# target to build an object file
src/vision/SectorTracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/SectorTracker.cpp.o
.PHONY : src/vision/SectorTracker.cpp.o

src/vision/SectorTracker.i: src/vision/SectorTracker.cpp.i
.PHONY : src/vision/SectorTracker.i

# target to preprocess a source file
src/vision/SectorTracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/SectorTracker.cpp.i
.PHONY : src/vision/SectorTracker.cpp.i

src/vision/SectorTracker.s: src/vision/SectorTracker.cpp.s
.PHONY : src/vision/SectorTracker.s

# target to generate assembly for a file
src/vision/SectorTracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/SectorTracker.cpp.s
.PHONY : src/vision/SectorTracker.cpp.s

src/vision/Thresholds.o: src/vision/Thresholds.cpp.o
.PHONY : src/vision/Thresholds.o

# target to build an object file
src/vision/Thresholds.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/Thresholds.cpp.o
.PHONY : src/vision/Thresholds.cpp.o

src/vision/Thresholds.i: src/vision/Thresholds.cpp.i
.PHONY : src/vision/Thresholds.i

# target to preprocess a source file
src/vision/Thresholds.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/Thresholds.cpp.i
.PHONY : src/vision/Thresholds.cpp.i

src/vision/Thresholds.s: src/vision/Thresholds.cpp.s
.PHONY : src/vision/Thresholds.s

# target to generate assembly for a file
src/vision/Thresholds.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/Thresholds.cpp.s
.PHONY : src/vision/Thresholds.cpp.s

src/vision/VisionMath.o: src/vision/VisionMath.cpp.o
.PHONY : src/vision/VisionMath.o

# target to build an object file
src/vision/VisionMath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/vision/VisionMath.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/VisionMath.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/vision/VisionMath.cpp.o
.PHONY : src/vision/VisionMath.cpp.o

src/vision/VisionMath.i: src/vision/VisionMath.cpp.i
.PHONY : src/vision/VisionMath.i

# target to preprocess a source file
src/vision/VisionMath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/vision/VisionMath.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/VisionMath.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/vision/VisionMath.cpp.i
.PHONY : src/vision/VisionMath.cpp.i

src/vision/VisionMath.s: src/vision/VisionMath.cpp.s
.PHONY : src/vision/VisionMath.s

# target to generate assembly for a file
src/vision/VisionMath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/vision/VisionMath.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/VisionMath.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/src/vision/VisionMath.cpp.s
.PHONY : src/vision/VisionMath.cpp.s

tests/MotionPoseTests.o: tests/MotionPoseTests.cpp.o
.PHONY : tests/MotionPoseTests.o

# target to build an object file
tests/MotionPoseTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_tests.dir/build.make CMakeFiles/ballalgo_motion_tests.dir/tests/MotionPoseTests.cpp.o
.PHONY : tests/MotionPoseTests.cpp.o

tests/MotionPoseTests.i: tests/MotionPoseTests.cpp.i
.PHONY : tests/MotionPoseTests.i

# target to preprocess a source file
tests/MotionPoseTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_tests.dir/build.make CMakeFiles/ballalgo_motion_tests.dir/tests/MotionPoseTests.cpp.i
.PHONY : tests/MotionPoseTests.cpp.i

tests/MotionPoseTests.s: tests/MotionPoseTests.cpp.s
.PHONY : tests/MotionPoseTests.s

# target to generate assembly for a file
tests/MotionPoseTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_tests.dir/build.make CMakeFiles/ballalgo_motion_tests.dir/tests/MotionPoseTests.cpp.s
.PHONY : tests/MotionPoseTests.cpp.s

tests/ProtocolTests.o: tests/ProtocolTests.cpp.o
.PHONY : tests/ProtocolTests.o

# target to build an object file
tests/ProtocolTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_protocol_tests.dir/build.make CMakeFiles/ballalgo_protocol_tests.dir/tests/ProtocolTests.cpp.o
.PHONY : tests/ProtocolTests.cpp.o

tests/ProtocolTests.i: tests/ProtocolTests.cpp.i
.PHONY : tests/ProtocolTests.i

# target to preprocess a source file
tests/ProtocolTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_protocol_tests.dir/build.make CMakeFiles/ballalgo_protocol_tests.dir/tests/ProtocolTests.cpp.i
.PHONY : tests/ProtocolTests.cpp.i

tests/ProtocolTests.s: tests/ProtocolTests.cpp.s
.PHONY : tests/ProtocolTests.s

# target to generate assembly for a file
tests/ProtocolTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_protocol_tests.dir/build.make CMakeFiles/ballalgo_protocol_tests.dir/tests/ProtocolTests.cpp.s
.PHONY : tests/ProtocolTests.cpp.s

tests/TeamCoordinationTests.o: tests/TeamCoordinationTests.cpp.o
.PHONY : tests/TeamCoordinationTests.o

# target to build an object file
tests/TeamCoordinationTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/tests/TeamCoordinationTests.cpp.o
.PHONY : tests/TeamCoordinationTests.cpp.o

tests/TeamCoordinationTests.i: tests/TeamCoordinationTests.cpp.i
.PHONY : tests/TeamCoordinationTests.i

# target to preprocess a source file
tests/TeamCoordinationTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/tests/TeamCoordinationTests.cpp.i
.PHONY : tests/TeamCoordinationTests.cpp.i

tests/TeamCoordinationTests.s: tests/TeamCoordinationTests.cpp.s
.PHONY : tests/TeamCoordinationTests.s

# target to generate assembly for a file
tests/TeamCoordinationTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_team_tests.dir/build.make CMakeFiles/ballalgo_team_tests.dir/tests/TeamCoordinationTests.cpp.s
.PHONY : tests/TeamCoordinationTests.cpp.s

tests/TrajectoryFrameTests.o: tests/TrajectoryFrameTests.cpp.o
.PHONY : tests/TrajectoryFrameTests.o

# target to build an object file
tests/TrajectoryFrameTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_frame_tests.dir/build.make CMakeFiles/ballalgo_frame_tests.dir/tests/TrajectoryFrameTests.cpp.o
.PHONY : tests/TrajectoryFrameTests.cpp.o

tests/TrajectoryFrameTests.i: tests/TrajectoryFrameTests.cpp.i
.PHONY : tests/TrajectoryFrameTests.i

# target to preprocess a source file
tests/TrajectoryFrameTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_frame_tests.dir/build.make CMakeFiles/ballalgo_frame_tests.dir/tests/TrajectoryFrameTests.cpp.i
.PHONY : tests/TrajectoryFrameTests.cpp.i

tests/TrajectoryFrameTests.s: tests/TrajectoryFrameTests.cpp.s
.PHONY : tests/TrajectoryFrameTests.s

# target to generate assembly for a file
tests/TrajectoryFrameTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_frame_tests.dir/build.make CMakeFiles/ballalgo_frame_tests.dir/tests/TrajectoryFrameTests.cpp.s
.PHONY : tests/TrajectoryFrameTests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... ballalgo"
	@echo "... ballalgo_frame_tests"
	@echo "... ballalgo_motion_core"
	@echo "... ballalgo_motion_tests"
	@echo "... ballalgo_planner_case"
	@echo "... ballalgo_protocol_tests"
	@echo "... ballalgo_team_tests"
	@echo "... src/FoxGloveSim/FoxgloveConfig.o"
	@echo "... src/FoxGloveSim/FoxgloveConfig.i"
	@echo "... src/FoxGloveSim/FoxgloveConfig.s"
	@echo "... src/FoxGloveSim/FoxgloveTelemetryPublisher.o"
	@echo "... src/FoxGloveSim/FoxgloveTelemetryPublisher.i"
	@echo "... src/FoxGloveSim/FoxgloveTelemetryPublisher.s"
	@echo "... src/camera/CameraCapture.o"
	@echo "... src/camera/CameraCapture.i"
	@echo "... src/camera/CameraCapture.s"
	@echo "... src/estimation/BallKalman.o"
	@echo "... src/estimation/BallKalman.i"
	@echo "... src/estimation/BallKalman.s"
	@echo "... src/estimation/PoseKalman.o"
	@echo "... src/estimation/PoseKalman.i"
	@echo "... src/estimation/PoseKalman.s"
	@echo "... src/io/GpioLidar.o"
	@echo "... src/io/GpioLidar.i"
	@echo "... src/io/GpioLidar.s"
	@echo "... src/io/RobotSerial.o"
	@echo "... src/io/RobotSerial.i"
	@echo "... src/io/RobotSerial.s"
	@echo "... src/lidar/Ld19Reader.o"
	@echo "... src/lidar/Ld19Reader.i"
	@echo "... src/lidar/Ld19Reader.s"
	@echo "... src/lidar/LidarDeskewer.o"
	@echo "... src/lidar/LidarDeskewer.i"
	@echo "... src/lidar/LidarDeskewer.s"
	@echo "... src/lidar/LidarLocalizer.o"
	@echo "... src/lidar/LidarLocalizer.i"
	@echo "... src/lidar/LidarLocalizer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/motion/AStar3D.o"
	@echo "... src/motion/AStar3D.i"
	@echo "... src/motion/AStar3D.s"
	@echo "... src/motion/ActionChunkPublisher.o"
	@echo "... src/motion/ActionChunkPublisher.i"
	@echo "... src/motion/ActionChunkPublisher.s"
	@echo "... src/motion/ClockSync.o"
	@echo "... src/motion/ClockSync.i"
	@echo "... src/motion/ClockSync.s"
	@echo "... src/motion/DefensePose.o"
	@echo "... src/motion/DefensePose.i"
	@echo "... src/motion/DefensePose.s"
	@echo "... src/motion/HermiteSpline.o"
	@echo "... src/motion/HermiteSpline.i"
	@echo "... src/motion/HermiteSpline.s"
	@echo "... src/motion/MotionPipeline.o"
	@echo "... src/motion/MotionPipeline.i"
	@echo "... src/motion/MotionPipeline.s"
	@echo "... src/motion/MotionPlanner.o"
	@echo "... src/motion/MotionPlanner.i"
	@echo "... src/motion/MotionPlanner.s"
	@echo "... src/motion/OffensePose.o"
	@echo "... src/motion/OffensePose.i"
	@echo "... src/motion/OffensePose.s"
	@echo "... src/motion/Protocol.o"
	@echo "... src/motion/Protocol.i"
	@echo "... src/motion/Protocol.s"
	@echo "... src/motion/StrikePose.o"
	@echo "... src/motion/StrikePose.i"
	@echo "... src/motion/StrikePose.s"
	@echo "... src/motion/TrajectoryReplay.o"
	@echo "... src/motion/TrajectoryReplay.i"
	@echo "... src/motion/TrajectoryReplay.s"
	@echo "... src/motion/TrajectoryReplayRunner.o"
	@echo "... src/motion/TrajectoryReplayRunner.i"
	@echo "... src/motion/TrajectoryReplayRunner.s"
	@echo "... src/motion/VelocityProfile.o"
	@echo "... src/motion/VelocityProfile.i"
	@echo "... src/motion/VelocityProfile.s"
	@echo "... src/planner/PlannerCaseMain.o"
	@echo "... src/planner/PlannerCaseMain.i"
	@echo "... src/planner/PlannerCaseMain.s"
	@echo "... src/team/RoleArbiter.o"
	@echo "... src/team/RoleArbiter.i"
	@echo "... src/team/RoleArbiter.s"
	@echo "... src/team/TeamBallFilter.o"
	@echo "... src/team/TeamBallFilter.i"
	@echo "... src/team/TeamBallFilter.s"
	@echo "... src/team/TeamLink.o"
	@echo "... src/team/TeamLink.i"
	@echo "... src/team/TeamLink.s"
	@echo "... src/team/TeamProto.o"
	@echo "... src/team/TeamProto.i"
	@echo "... src/team/TeamProto.s"
	@echo "... src/vision/SectorTracker.o"
	@echo "... src/vision/SectorTracker.i"
	@echo "... src/vision/SectorTracker.s"
	@echo "... src/vision/Thresholds.o"
	@echo "... src/vision/Thresholds.i"
	@echo "... src/vision/Thresholds.s"
	@echo "... src/vision/VisionMath.o"
	@echo "... src/vision/VisionMath.i"
	@echo "... src/vision/VisionMath.s"
	@echo "... tests/MotionPoseTests.o"
	@echo "... tests/MotionPoseTests.i"
	@echo "... tests/MotionPoseTests.s"
	@echo "... tests/ProtocolTests.o"
	@echo "... tests/ProtocolTests.i"
	@echo "... tests/ProtocolTests.s"
	@echo "... tests/TeamCoordinationTests.o"
	@echo "... tests/TeamCoordinationTests.i"
	@echo "... tests/TeamCoordinationTests.s"
	@echo "... tests/TrajectoryFrameTests.o"
	@echo "... tests/TrajectoryFrameTests.i"
	@echo "... tests/TrajectoryFrameTests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

