# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aniket/BallAlgo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aniket/BallAlgo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aniket/BallAlgo/CMakeFiles /home/aniket/BallAlgo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aniket/BallAlgo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ballalgo_motion_core

# Build rule for target.
ballalgo_motion_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo_motion_core
.PHONY : ballalgo_motion_core

# fast build rule for target.
ballalgo_motion_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/build
.PHONY : ballalgo_motion_core/fast

#=============================================================================
# Target rules for targets named ballalgo_sim_core

# Build rule for target.
ballalgo_sim_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo_sim_core
.PHONY : ballalgo_sim_core

# fast build rule for target.
ballalgo_sim_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/build
.PHONY : ballalgo_sim_core/fast

#=============================================================================
# Target rules for targets named ballalgo

# Build rule for target.
ballalgo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo
.PHONY : ballalgo

# fast build rule for target.
ballalgo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/build
.PHONY : ballalgo/fast

#=============================================================================
# Target rules for targets named ballalgo_sim

# Build rule for target.
ballalgo_sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo_sim
.PHONY : ballalgo_sim

# fast build rule for target.
ballalgo_sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim.dir/build.make CMakeFiles/ballalgo_sim.dir/build
.PHONY : ballalgo_sim/fast

#=============================================================================
# Target rules for targets named ballalgo_planner_bench

# Build rule for target.
ballalgo_planner_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ballalgo_planner_bench
.PHONY : ballalgo_planner_bench

# fast build rule for target.
ballalgo_planner_bench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_bench.dir/build.make CMakeFiles/ballalgo_planner_bench.dir/build
.PHONY : ballalgo_planner_bench/fast

sim/SimulationArtifactWriter.o: sim/SimulationArtifactWriter.cpp.o
.PHONY : sim/SimulationArtifactWriter.o

# target to build an object file
sim/SimulationArtifactWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationArtifactWriter.cpp.o
.PHONY : sim/SimulationArtifactWriter.cpp.o

sim/SimulationArtifactWriter.i: sim/SimulationArtifactWriter.cpp.i
.PHONY : sim/SimulationArtifactWriter.i

# target to preprocess a source file
sim/SimulationArtifactWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationArtifactWriter.cpp.i
.PHONY : sim/SimulationArtifactWriter.cpp.i

sim/SimulationArtifactWriter.s: sim/SimulationArtifactWriter.cpp.s
.PHONY : sim/SimulationArtifactWriter.s

# target to generate assembly for a file
sim/SimulationArtifactWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationArtifactWriter.cpp.s
.PHONY : sim/SimulationArtifactWriter.cpp.s

sim/SimulationCli.o: sim/SimulationCli.cpp.o
.PHONY : sim/SimulationCli.o

# target to build an object file
sim/SimulationCli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationCli.cpp.o
.PHONY : sim/SimulationCli.cpp.o

sim/SimulationCli.i: sim/SimulationCli.cpp.i
.PHONY : sim/SimulationCli.i

# target to preprocess a source file
sim/SimulationCli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationCli.cpp.i
.PHONY : sim/SimulationCli.cpp.i

sim/SimulationCli.s: sim/SimulationCli.cpp.s
.PHONY : sim/SimulationCli.s

# target to generate assembly for a file
sim/SimulationCli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationCli.cpp.s
.PHONY : sim/SimulationCli.cpp.s

sim/SimulationCore.o: sim/SimulationCore.cpp.o
.PHONY : sim/SimulationCore.o

# target to build an object file
sim/SimulationCore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationCore.cpp.o
.PHONY : sim/SimulationCore.cpp.o

sim/SimulationCore.i: sim/SimulationCore.cpp.i
.PHONY : sim/SimulationCore.i

# target to preprocess a source file
sim/SimulationCore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationCore.cpp.i
.PHONY : sim/SimulationCore.cpp.i

sim/SimulationCore.s: sim/SimulationCore.cpp.s
.PHONY : sim/SimulationCore.s

# target to generate assembly for a file
sim/SimulationCore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationCore.cpp.s
.PHONY : sim/SimulationCore.cpp.s

sim/SimulationMath.o: sim/SimulationMath.cpp.o
.PHONY : sim/SimulationMath.o

# target to build an object file
sim/SimulationMath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationMath.cpp.o
.PHONY : sim/SimulationMath.cpp.o

sim/SimulationMath.i: sim/SimulationMath.cpp.i
.PHONY : sim/SimulationMath.i

# target to preprocess a source file
sim/SimulationMath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationMath.cpp.i
.PHONY : sim/SimulationMath.cpp.i

sim/SimulationMath.s: sim/SimulationMath.cpp.s
.PHONY : sim/SimulationMath.s

# target to generate assembly for a file
sim/SimulationMath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationMath.cpp.s
.PHONY : sim/SimulationMath.cpp.s

sim/SimulationRunner.o: sim/SimulationRunner.cpp.o
.PHONY : sim/SimulationRunner.o

# target to build an object file
sim/SimulationRunner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationRunner.cpp.o
.PHONY : sim/SimulationRunner.cpp.o

sim/SimulationRunner.i: sim/SimulationRunner.cpp.i
.PHONY : sim/SimulationRunner.i

# target to preprocess a source file
sim/SimulationRunner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationRunner.cpp.i
.PHONY : sim/SimulationRunner.cpp.i

sim/SimulationRunner.s: sim/SimulationRunner.cpp.s
.PHONY : sim/SimulationRunner.s

# target to generate assembly for a file
sim/SimulationRunner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim_core.dir/build.make CMakeFiles/ballalgo_sim_core.dir/sim/SimulationRunner.cpp.s
.PHONY : sim/SimulationRunner.cpp.s

sim/ballalgo_sim.o: sim/ballalgo_sim.cpp.o
.PHONY : sim/ballalgo_sim.o

# target to build an object file
sim/ballalgo_sim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim.dir/build.make CMakeFiles/ballalgo_sim.dir/sim/ballalgo_sim.cpp.o
.PHONY : sim/ballalgo_sim.cpp.o

sim/ballalgo_sim.i: sim/ballalgo_sim.cpp.i
.PHONY : sim/ballalgo_sim.i

# target to preprocess a source file
sim/ballalgo_sim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim.dir/build.make CMakeFiles/ballalgo_sim.dir/sim/ballalgo_sim.cpp.i
.PHONY : sim/ballalgo_sim.cpp.i

sim/ballalgo_sim.s: sim/ballalgo_sim.cpp.s
.PHONY : sim/ballalgo_sim.s

# target to generate assembly for a file
sim/ballalgo_sim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_sim.dir/build.make CMakeFiles/ballalgo_sim.dir/sim/ballalgo_sim.cpp.s
.PHONY : sim/ballalgo_sim.cpp.s

src/FoxGloveSim/FoxgloveConfig.o: src/FoxGloveSim/FoxgloveConfig.cpp.o
.PHONY : src/FoxGloveSim/FoxgloveConfig.o

# target to build an object file
src/FoxGloveSim/FoxgloveConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveConfig.cpp.o
.PHONY : src/FoxGloveSim/FoxgloveConfig.cpp.o

src/FoxGloveSim/FoxgloveConfig.i: src/FoxGloveSim/FoxgloveConfig.cpp.i
.PHONY : src/FoxGloveSim/FoxgloveConfig.i

# target to preprocess a source file
src/FoxGloveSim/FoxgloveConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveConfig.cpp.i
.PHONY : src/FoxGloveSim/FoxgloveConfig.cpp.i

src/FoxGloveSim/FoxgloveConfig.s: src/FoxGloveSim/FoxgloveConfig.cpp.s
.PHONY : src/FoxGloveSim/FoxgloveConfig.s

# target to generate assembly for a file
src/FoxGloveSim/FoxgloveConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveConfig.cpp.s
.PHONY : src/FoxGloveSim/FoxgloveConfig.cpp.s

src/FoxGloveSim/FoxgloveTelemetryPublisher.o: src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.o
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.o

# target to build an object file
src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.o
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.o

src/FoxGloveSim/FoxgloveTelemetryPublisher.i: src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.i
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.i

# target to preprocess a source file
src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.i
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.i

src/FoxGloveSim/FoxgloveTelemetryPublisher.s: src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.s
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.s

# target to generate assembly for a file
src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.s
.PHONY : src/FoxGloveSim/FoxgloveTelemetryPublisher.cpp.s

src/camera/CameraCapture.o: src/camera/CameraCapture.cpp.o
.PHONY : src/camera/CameraCapture.o

# target to build an object file
src/camera/CameraCapture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/camera/CameraCapture.cpp.o
.PHONY : src/camera/CameraCapture.cpp.o

src/camera/CameraCapture.i: src/camera/CameraCapture.cpp.i
.PHONY : src/camera/CameraCapture.i

# target to preprocess a source file
src/camera/CameraCapture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/camera/CameraCapture.cpp.i
.PHONY : src/camera/CameraCapture.cpp.i

src/camera/CameraCapture.s: src/camera/CameraCapture.cpp.s
.PHONY : src/camera/CameraCapture.s

# target to generate assembly for a file
src/camera/CameraCapture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/camera/CameraCapture.cpp.s
.PHONY : src/camera/CameraCapture.cpp.s

src/estimation/BallKalman.o: src/estimation/BallKalman.cpp.o
.PHONY : src/estimation/BallKalman.o

# target to build an object file
src/estimation/BallKalman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/BallKalman.cpp.o
.PHONY : src/estimation/BallKalman.cpp.o

src/estimation/BallKalman.i: src/estimation/BallKalman.cpp.i
.PHONY : src/estimation/BallKalman.i

# target to preprocess a source file
src/estimation/BallKalman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/BallKalman.cpp.i
.PHONY : src/estimation/BallKalman.cpp.i

src/estimation/BallKalman.s: src/estimation/BallKalman.cpp.s
.PHONY : src/estimation/BallKalman.s

# target to generate assembly for a file
src/estimation/BallKalman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/BallKalman.cpp.s
.PHONY : src/estimation/BallKalman.cpp.s

src/estimation/PoseKalman.o: src/estimation/PoseKalman.cpp.o
.PHONY : src/estimation/PoseKalman.o

# target to build an object file
src/estimation/PoseKalman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/PoseKalman.cpp.o
.PHONY : src/estimation/PoseKalman.cpp.o

src/estimation/PoseKalman.i: src/estimation/PoseKalman.cpp.i
.PHONY : src/estimation/PoseKalman.i

# target to preprocess a source file
src/estimation/PoseKalman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/PoseKalman.cpp.i
.PHONY : src/estimation/PoseKalman.cpp.i

src/estimation/PoseKalman.s: src/estimation/PoseKalman.cpp.s
.PHONY : src/estimation/PoseKalman.s

# target to generate assembly for a file
src/estimation/PoseKalman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/estimation/PoseKalman.cpp.s
.PHONY : src/estimation/PoseKalman.cpp.s

src/io/GpioLidar.o: src/io/GpioLidar.cpp.o
.PHONY : src/io/GpioLidar.o

# target to build an object file
src/io/GpioLidar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/GpioLidar.cpp.o
.PHONY : src/io/GpioLidar.cpp.o

src/io/GpioLidar.i: src/io/GpioLidar.cpp.i
.PHONY : src/io/GpioLidar.i

# target to preprocess a source file
src/io/GpioLidar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/GpioLidar.cpp.i
.PHONY : src/io/GpioLidar.cpp.i

src/io/GpioLidar.s: src/io/GpioLidar.cpp.s
.PHONY : src/io/GpioLidar.s

# target to generate assembly for a file
src/io/GpioLidar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/GpioLidar.cpp.s
.PHONY : src/io/GpioLidar.cpp.s

src/io/RobotSerial.o: src/io/RobotSerial.cpp.o
.PHONY : src/io/RobotSerial.o

# target to build an object file
src/io/RobotSerial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/RobotSerial.cpp.o
.PHONY : src/io/RobotSerial.cpp.o

src/io/RobotSerial.i: src/io/RobotSerial.cpp.i
.PHONY : src/io/RobotSerial.i

# target to preprocess a source file
src/io/RobotSerial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/RobotSerial.cpp.i
.PHONY : src/io/RobotSerial.cpp.i

src/io/RobotSerial.s: src/io/RobotSerial.cpp.s
.PHONY : src/io/RobotSerial.s

# target to generate assembly for a file
src/io/RobotSerial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/io/RobotSerial.cpp.s
.PHONY : src/io/RobotSerial.cpp.s

src/lidar/Ld19Reader.o: src/lidar/Ld19Reader.cpp.o
.PHONY : src/lidar/Ld19Reader.o

# target to build an object file
src/lidar/Ld19Reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/Ld19Reader.cpp.o
.PHONY : src/lidar/Ld19Reader.cpp.o

src/lidar/Ld19Reader.i: src/lidar/Ld19Reader.cpp.i
.PHONY : src/lidar/Ld19Reader.i

# target to preprocess a source file
src/lidar/Ld19Reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/Ld19Reader.cpp.i
.PHONY : src/lidar/Ld19Reader.cpp.i

src/lidar/Ld19Reader.s: src/lidar/Ld19Reader.cpp.s
.PHONY : src/lidar/Ld19Reader.s

# target to generate assembly for a file
src/lidar/Ld19Reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/Ld19Reader.cpp.s
.PHONY : src/lidar/Ld19Reader.cpp.s

src/lidar/LidarLocalizer.o: src/lidar/LidarLocalizer.cpp.o
.PHONY : src/lidar/LidarLocalizer.o

# target to build an object file
src/lidar/LidarLocalizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/LidarLocalizer.cpp.o
.PHONY : src/lidar/LidarLocalizer.cpp.o

src/lidar/LidarLocalizer.i: src/lidar/LidarLocalizer.cpp.i
.PHONY : src/lidar/LidarLocalizer.i

# target to preprocess a source file
src/lidar/LidarLocalizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/LidarLocalizer.cpp.i
.PHONY : src/lidar/LidarLocalizer.cpp.i

src/lidar/LidarLocalizer.s: src/lidar/LidarLocalizer.cpp.s
.PHONY : src/lidar/LidarLocalizer.s

# target to generate assembly for a file
src/lidar/LidarLocalizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/lidar/LidarLocalizer.cpp.s
.PHONY : src/lidar/LidarLocalizer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/motion/AStar3D.o: src/motion/AStar3D.cpp.o
.PHONY : src/motion/AStar3D.o

# target to build an object file
src/motion/AStar3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/AStar3D.cpp.o
.PHONY : src/motion/AStar3D.cpp.o

src/motion/AStar3D.i: src/motion/AStar3D.cpp.i
.PHONY : src/motion/AStar3D.i

# target to preprocess a source file
src/motion/AStar3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/AStar3D.cpp.i
.PHONY : src/motion/AStar3D.cpp.i

src/motion/AStar3D.s: src/motion/AStar3D.cpp.s
.PHONY : src/motion/AStar3D.s

# target to generate assembly for a file
src/motion/AStar3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/AStar3D.cpp.s
.PHONY : src/motion/AStar3D.cpp.s

src/motion/ActionChunkPublisher.o: src/motion/ActionChunkPublisher.cpp.o
.PHONY : src/motion/ActionChunkPublisher.o

# target to build an object file
src/motion/ActionChunkPublisher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ActionChunkPublisher.cpp.o
.PHONY : src/motion/ActionChunkPublisher.cpp.o

src/motion/ActionChunkPublisher.i: src/motion/ActionChunkPublisher.cpp.i
.PHONY : src/motion/ActionChunkPublisher.i

# target to preprocess a source file
src/motion/ActionChunkPublisher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ActionChunkPublisher.cpp.i
.PHONY : src/motion/ActionChunkPublisher.cpp.i

src/motion/ActionChunkPublisher.s: src/motion/ActionChunkPublisher.cpp.s
.PHONY : src/motion/ActionChunkPublisher.s

# target to generate assembly for a file
src/motion/ActionChunkPublisher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ActionChunkPublisher.cpp.s
.PHONY : src/motion/ActionChunkPublisher.cpp.s

src/motion/ClockSync.o: src/motion/ClockSync.cpp.o
.PHONY : src/motion/ClockSync.o

# target to build an object file
src/motion/ClockSync.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ClockSync.cpp.o
.PHONY : src/motion/ClockSync.cpp.o

src/motion/ClockSync.i: src/motion/ClockSync.cpp.i
.PHONY : src/motion/ClockSync.i

# target to preprocess a source file
src/motion/ClockSync.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ClockSync.cpp.i
.PHONY : src/motion/ClockSync.cpp.i

src/motion/ClockSync.s: src/motion/ClockSync.cpp.s
.PHONY : src/motion/ClockSync.s

# target to generate assembly for a file
src/motion/ClockSync.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/ClockSync.cpp.s
.PHONY : src/motion/ClockSync.cpp.s

src/motion/HermiteSpline.o: src/motion/HermiteSpline.cpp.o
.PHONY : src/motion/HermiteSpline.o

# target to build an object file
src/motion/HermiteSpline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/HermiteSpline.cpp.o
.PHONY : src/motion/HermiteSpline.cpp.o

src/motion/HermiteSpline.i: src/motion/HermiteSpline.cpp.i
.PHONY : src/motion/HermiteSpline.i

# target to preprocess a source file
src/motion/HermiteSpline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/HermiteSpline.cpp.i
.PHONY : src/motion/HermiteSpline.cpp.i

src/motion/HermiteSpline.s: src/motion/HermiteSpline.cpp.s
.PHONY : src/motion/HermiteSpline.s

# target to generate assembly for a file
src/motion/HermiteSpline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/HermiteSpline.cpp.s
.PHONY : src/motion/HermiteSpline.cpp.s

src/motion/MotionPipeline.o: src/motion/MotionPipeline.cpp.o
.PHONY : src/motion/MotionPipeline.o

# target to build an object file
src/motion/MotionPipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/MotionPipeline.cpp.o
.PHONY : src/motion/MotionPipeline.cpp.o

src/motion/MotionPipeline.i: src/motion/MotionPipeline.cpp.i
.PHONY : src/motion/MotionPipeline.i

# target to preprocess a source file
src/motion/MotionPipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/MotionPipeline.cpp.i
.PHONY : src/motion/MotionPipeline.cpp.i

src/motion/MotionPipeline.s: src/motion/MotionPipeline.cpp.s
.PHONY : src/motion/MotionPipeline.s

# target to generate assembly for a file
src/motion/MotionPipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/MotionPipeline.cpp.s
.PHONY : src/motion/MotionPipeline.cpp.s

src/motion/MotionPlanner.o: src/motion/MotionPlanner.cpp.o
.PHONY : src/motion/MotionPlanner.o

# target to build an object file
src/motion/MotionPlanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/MotionPlanner.cpp.o
.PHONY : src/motion/MotionPlanner.cpp.o

src/motion/MotionPlanner.i: src/motion/MotionPlanner.cpp.i
.PHONY : src/motion/MotionPlanner.i

# target to preprocess a source file
src/motion/MotionPlanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/MotionPlanner.cpp.i
.PHONY : src/motion/MotionPlanner.cpp.i

src/motion/MotionPlanner.s: src/motion/MotionPlanner.cpp.s
.PHONY : src/motion/MotionPlanner.s

# target to generate assembly for a file
src/motion/MotionPlanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/MotionPlanner.cpp.s
.PHONY : src/motion/MotionPlanner.cpp.s

src/motion/Protocol.o: src/motion/Protocol.cpp.o
.PHONY : src/motion/Protocol.o

# target to build an object file
src/motion/Protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/Protocol.cpp.o
.PHONY : src/motion/Protocol.cpp.o

src/motion/Protocol.i: src/motion/Protocol.cpp.i
.PHONY : src/motion/Protocol.i

# target to preprocess a source file
src/motion/Protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/Protocol.cpp.i
.PHONY : src/motion/Protocol.cpp.i

src/motion/Protocol.s: src/motion/Protocol.cpp.s
.PHONY : src/motion/Protocol.s

# target to generate assembly for a file
src/motion/Protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/motion/Protocol.cpp.s
.PHONY : src/motion/Protocol.cpp.s

src/motion/StrikePose.o: src/motion/StrikePose.cpp.o
.PHONY : src/motion/StrikePose.o

# target to build an object file
src/motion/StrikePose.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/StrikePose.cpp.o
.PHONY : src/motion/StrikePose.cpp.o

src/motion/StrikePose.i: src/motion/StrikePose.cpp.i
.PHONY : src/motion/StrikePose.i

# target to preprocess a source file
src/motion/StrikePose.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/StrikePose.cpp.i
.PHONY : src/motion/StrikePose.cpp.i

src/motion/StrikePose.s: src/motion/StrikePose.cpp.s
.PHONY : src/motion/StrikePose.s

# target to generate assembly for a file
src/motion/StrikePose.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/StrikePose.cpp.s
.PHONY : src/motion/StrikePose.cpp.s

src/motion/VelocityProfile.o: src/motion/VelocityProfile.cpp.o
.PHONY : src/motion/VelocityProfile.o

# target to build an object file
src/motion/VelocityProfile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/VelocityProfile.cpp.o
.PHONY : src/motion/VelocityProfile.cpp.o

src/motion/VelocityProfile.i: src/motion/VelocityProfile.cpp.i
.PHONY : src/motion/VelocityProfile.i

# target to preprocess a source file
src/motion/VelocityProfile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/VelocityProfile.cpp.i
.PHONY : src/motion/VelocityProfile.cpp.i

src/motion/VelocityProfile.s: src/motion/VelocityProfile.cpp.s
.PHONY : src/motion/VelocityProfile.s

# target to generate assembly for a file
src/motion/VelocityProfile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/motion/VelocityProfile.cpp.s
.PHONY : src/motion/VelocityProfile.cpp.s

src/vision/SectorTracker.o: src/vision/SectorTracker.cpp.o
.PHONY : src/vision/SectorTracker.o

# target to build an object file
src/vision/SectorTracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/SectorTracker.cpp.o
.PHONY : src/vision/SectorTracker.cpp.o

src/vision/SectorTracker.i: src/vision/SectorTracker.cpp.i
.PHONY : src/vision/SectorTracker.i

# target to preprocess a source file
src/vision/SectorTracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/SectorTracker.cpp.i
.PHONY : src/vision/SectorTracker.cpp.i

src/vision/SectorTracker.s: src/vision/SectorTracker.cpp.s
.PHONY : src/vision/SectorTracker.s

# target to generate assembly for a file
src/vision/SectorTracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/SectorTracker.cpp.s
.PHONY : src/vision/SectorTracker.cpp.s

src/vision/Thresholds.o: src/vision/Thresholds.cpp.o
.PHONY : src/vision/Thresholds.o

# target to build an object file
src/vision/Thresholds.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/Thresholds.cpp.o
.PHONY : src/vision/Thresholds.cpp.o

src/vision/Thresholds.i: src/vision/Thresholds.cpp.i
.PHONY : src/vision/Thresholds.i

# target to preprocess a source file
src/vision/Thresholds.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/Thresholds.cpp.i
.PHONY : src/vision/Thresholds.cpp.i

src/vision/Thresholds.s: src/vision/Thresholds.cpp.s
.PHONY : src/vision/Thresholds.s

# target to generate assembly for a file
src/vision/Thresholds.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/Thresholds.cpp.s
.PHONY : src/vision/Thresholds.cpp.s

src/vision/VisionMath.o: src/vision/VisionMath.cpp.o
.PHONY : src/vision/VisionMath.o

# target to build an object file
src/vision/VisionMath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/vision/VisionMath.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/VisionMath.cpp.o
.PHONY : src/vision/VisionMath.cpp.o

src/vision/VisionMath.i: src/vision/VisionMath.cpp.i
.PHONY : src/vision/VisionMath.i

# target to preprocess a source file
src/vision/VisionMath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/vision/VisionMath.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/VisionMath.cpp.i
.PHONY : src/vision/VisionMath.cpp.i

src/vision/VisionMath.s: src/vision/VisionMath.cpp.s
.PHONY : src/vision/VisionMath.s

# target to generate assembly for a file
src/vision/VisionMath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_motion_core.dir/build.make CMakeFiles/ballalgo_motion_core.dir/src/vision/VisionMath.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo.dir/build.make CMakeFiles/ballalgo.dir/src/vision/VisionMath.cpp.s
.PHONY : src/vision/VisionMath.cpp.s

testing/planner_bench.o: testing/planner_bench.cpp.o
.PHONY : testing/planner_bench.o

# target to build an object file
testing/planner_bench.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_bench.dir/build.make CMakeFiles/ballalgo_planner_bench.dir/testing/planner_bench.cpp.o
.PHONY : testing/planner_bench.cpp.o

testing/planner_bench.i: testing/planner_bench.cpp.i
.PHONY : testing/planner_bench.i

# target to preprocess a source file
testing/planner_bench.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_bench.dir/build.make CMakeFiles/ballalgo_planner_bench.dir/testing/planner_bench.cpp.i
.PHONY : testing/planner_bench.cpp.i

testing/planner_bench.s: testing/planner_bench.cpp.s
.PHONY : testing/planner_bench.s

# target to generate assembly for a file
testing/planner_bench.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ballalgo_planner_bench.dir/build.make CMakeFiles/ballalgo_planner_bench.dir/testing/planner_bench.cpp.s
.PHONY : testing/planner_bench.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ballalgo"
	@echo "... ballalgo_motion_core"
	@echo "... ballalgo_planner_bench"
	@echo "... ballalgo_sim"
	@echo "... ballalgo_sim_core"
	@echo "... sim/SimulationArtifactWriter.o"
	@echo "... sim/SimulationArtifactWriter.i"
	@echo "... sim/SimulationArtifactWriter.s"
	@echo "... sim/SimulationCli.o"
	@echo "... sim/SimulationCli.i"
	@echo "... sim/SimulationCli.s"
	@echo "... sim/SimulationCore.o"
	@echo "... sim/SimulationCore.i"
	@echo "... sim/SimulationCore.s"
	@echo "... sim/SimulationMath.o"
	@echo "... sim/SimulationMath.i"
	@echo "... sim/SimulationMath.s"
	@echo "... sim/SimulationRunner.o"
	@echo "... sim/SimulationRunner.i"
	@echo "... sim/SimulationRunner.s"
	@echo "... sim/ballalgo_sim.o"
	@echo "... sim/ballalgo_sim.i"
	@echo "... sim/ballalgo_sim.s"
	@echo "... src/FoxGloveSim/FoxgloveConfig.o"
	@echo "... src/FoxGloveSim/FoxgloveConfig.i"
	@echo "... src/FoxGloveSim/FoxgloveConfig.s"
	@echo "... src/FoxGloveSim/FoxgloveTelemetryPublisher.o"
	@echo "... src/FoxGloveSim/FoxgloveTelemetryPublisher.i"
	@echo "... src/FoxGloveSim/FoxgloveTelemetryPublisher.s"
	@echo "... src/camera/CameraCapture.o"
	@echo "... src/camera/CameraCapture.i"
	@echo "... src/camera/CameraCapture.s"
	@echo "... src/estimation/BallKalman.o"
	@echo "... src/estimation/BallKalman.i"
	@echo "... src/estimation/BallKalman.s"
	@echo "... src/estimation/PoseKalman.o"
	@echo "... src/estimation/PoseKalman.i"
	@echo "... src/estimation/PoseKalman.s"
	@echo "... src/io/GpioLidar.o"
	@echo "... src/io/GpioLidar.i"
	@echo "... src/io/GpioLidar.s"
	@echo "... src/io/RobotSerial.o"
	@echo "... src/io/RobotSerial.i"
	@echo "... src/io/RobotSerial.s"
	@echo "... src/lidar/Ld19Reader.o"
	@echo "... src/lidar/Ld19Reader.i"
	@echo "... src/lidar/Ld19Reader.s"
	@echo "... src/lidar/LidarLocalizer.o"
	@echo "... src/lidar/LidarLocalizer.i"
	@echo "... src/lidar/LidarLocalizer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/motion/AStar3D.o"
	@echo "... src/motion/AStar3D.i"
	@echo "... src/motion/AStar3D.s"
	@echo "... src/motion/ActionChunkPublisher.o"
	@echo "... src/motion/ActionChunkPublisher.i"
	@echo "... src/motion/ActionChunkPublisher.s"
	@echo "... src/motion/ClockSync.o"
	@echo "... src/motion/ClockSync.i"
	@echo "... src/motion/ClockSync.s"
	@echo "... src/motion/HermiteSpline.o"
	@echo "... src/motion/HermiteSpline.i"
	@echo "... src/motion/HermiteSpline.s"
	@echo "... src/motion/MotionPipeline.o"
	@echo "... src/motion/MotionPipeline.i"
	@echo "... src/motion/MotionPipeline.s"
	@echo "... src/motion/MotionPlanner.o"
	@echo "... src/motion/MotionPlanner.i"
	@echo "... src/motion/MotionPlanner.s"
	@echo "... src/motion/Protocol.o"
	@echo "... src/motion/Protocol.i"
	@echo "... src/motion/Protocol.s"
	@echo "... src/motion/StrikePose.o"
	@echo "... src/motion/StrikePose.i"
	@echo "... src/motion/StrikePose.s"
	@echo "... src/motion/VelocityProfile.o"
	@echo "... src/motion/VelocityProfile.i"
	@echo "... src/motion/VelocityProfile.s"
	@echo "... src/vision/SectorTracker.o"
	@echo "... src/vision/SectorTracker.i"
	@echo "... src/vision/SectorTracker.s"
	@echo "... src/vision/Thresholds.o"
	@echo "... src/vision/Thresholds.i"
	@echo "... src/vision/Thresholds.s"
	@echo "... src/vision/VisionMath.o"
	@echo "... src/vision/VisionMath.i"
	@echo "... src/vision/VisionMath.s"
	@echo "... testing/planner_bench.o"
	@echo "... testing/planner_bench.i"
	@echo "... testing/planner_bench.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

